### ISSUE TITLE
Immich requires version of 0.1.11 

### ISSUE THREAD

**Issue by MGlants** [chkpwd/cdpgvecto.rs#4]
https://github.com/immich-app/immich/issues/5759#issuecomment-1859106095
As issue suggestes, 0.1.13 is not working yet, could you build for 0.1.11

**Comment by chkpwd** [comment]
Thank you. Issue should be fixed now. I downgraded the version to v0.1.11. Fair warning, I have not tested it so if you can kindly check if it works with the respective tags.

**Comment by MGlants** [comment]
Thank you for quick response,  as for now 
`[Nest] 8  - 12/20/2023, 12:51:12 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: pgvecto.rs: pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full Postgresql log to get more information.`

**Comment by MGlants** [comment]
> Thank you for quick response, as for now `[Nest] 8 - 12/20/2023, 12:51:12 AM ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)... QueryFailedError: pgvecto.rs: pgvecto.rs: IPC connection is closed unexpected. ADVICE: The error is raisen by background worker errors. Please check the full Postgresql log to get more information. at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async AddCLIPEmbeddingIndex1700713994428.up (/usr/src/app/dist/infra/migrations/1700713994428-AddCLIPEmbeddingIndex.js:9:9) at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17) at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35) at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17).`

fixed itself after a while

**Comment by chkpwd** [comment]
If the pod lifecycle hasn't terminated. Can you exec into the pod and paste the output of ``/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19``?

**Comment by MGlants** [comment]
than you for you efforts,  now issue resolved =*
